version: '3'

services:
  nginx-reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "${NGINX_HOST_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONF_D_PATH}:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    networks:
      - ${PROXY_NETWORK}
    depends_on:
      - certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - nginx-reverse-proxy
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME}

volumes:
  certbot-etc:
  certbot-var:
  webroot:

networks:
  ${PROXY_NETWORK}:
    external: true