version: '3'
services:
  nginx-reverse-proxy:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONF_D_PATH}:/etc/nginx/conf.d:ro
      - ${NGINX_SSL_CERT_PATH}:/etc/nginx/ssl/fullchain.pem:ro
      - ${NGINX_SSL_KEY_PATH}:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - ${PROXY_NETWORK}
    restart: unless-stopped

networks:
  ${PROXY_NETWORK}:
    external: true